"""Fallback word list for when no valid words are found in recent messages."""

from __future__ import annotations

FALLBACK_WORDS: list[str] = [
    "abacaxi", "acordo", "agenda", "alegria", "almoço", "altura", "amigo",
    "animal", "arquivo", "artigo", "avenida", "banana", "bandeira", "barulho",
    "basquete", "batalha", "bebida", "bilhete", "biologia", "biscoito",
    "bloquear", "boletim", "bolinha", "boneca", "branco", "brasil",
    "brigada", "cadeira", "caderno", "calcular", "caminho", "campanha",
    "caneta", "capital", "carinho", "carnaval", "castelo", "cavalo",
    "celular", "cerveja", "cinema", "cidade", "classe", "coelho",
    "colega", "comida", "compras", "computador", "comunidade", "conexão",
    "conselho", "conversa", "corrida", "cozinha", "criança", "cultura",
    "dançar", "debate", "decisão", "dentista", "desafio", "desenho",
    "destino", "digital", "dinheiro", "diploma", "direção", "diversão",
    "domingo", "dragão", "economia", "edifício", "educação", "elefante",
    "empresa", "energia", "enigma", "entrada", "equipe", "escola",
    "espaço", "esporte", "estação", "estrada", "estrela", "evento",
    "exemplo", "família", "fantasia", "farmácia", "fazenda", "feriado",
    "ferramentas", "festival", "figurinha", "filosofia", "fórmula",
    "fotografia", "futebol", "galáxia", "galinha", "garagem", "gelado",
    "girafa", "governo", "gramática", "guerra", "guitarra", "história",
    "hospital", "humano", "ideia", "igreja", "imagem", "infância",
    "informação", "internet", "inverno", "janela", "jardim", "jornal",
    "jovem", "justiça", "lagarto", "laranja", "legenda", "leitura",
    "liberdade", "limonada", "linguagem", "livro", "lógica", "lugar",
    "macarrão", "madeira", "mágica", "mangaba", "manhã", "maquiagem",
    "máquina", "medicina", "melodia", "memória", "mercado", "metrô",
    "militar", "ministro", "mistério", "moeda", "momento", "montanha",
    "morango", "motor", "mudança", "mulher", "mundo", "museu",
    "música", "natural", "navegar", "negócio", "nobre", "notícia",
    "número", "oceano", "oficina", "olhar", "opinião", "oportunidade",
    "organizar", "outono", "paciência", "padaria", "paisagem", "palavra",
    "panela", "papagaio", "parque", "partido", "passagem", "passarinho",
    "pedreiro", "peixe", "pensamento", "pequeno", "pessoa", "pintura",
    "planeta", "planta", "poesia", "político", "portal", "prática",
    "presente", "primavera", "princesa", "problema", "professor",
    "programa", "projeto", "proteção", "público", "queijo", "questão",
    "quilômetro", "quintal", "rainha", "rádio", "receita", "região",
    "relógio", "remédio", "respeito", "restaurante", "revista", "robótica",
    "sábado", "sabedoria", "salário", "sandália", "saudade", "segredo",
    "semana", "senhora", "silêncio", "sistema", "sociedade", "soldado",
    "sorriso", "surpresa", "teclado", "telefone", "televisão", "tempestade",
    "trabalho", "tradição", "trânsito", "turismo", "universo", "vacina",
    "valente", "verdade", "viagem", "violão", "vitória", "vizinho",
    "xadrez", "zoológico",
]
